# SEO研究工具配置文件示例
# 保存为config.yaml或config.json格式

# 目标网站域名
domain: "aircon88.innovisle.net"

# 区域设置 (com, com.hk, co.jp等)
region: "com.hk"

# 搜索引擎设置 (google, bing)
search_engine: "google"

# 搜索结果页数
pages: 10

# 请求延迟设置(秒)
delay_min: 0.0
delay_max: 2.0

# 输出文件名
output: "aircon_keyword_results.xlsx"

# 关键词列表
keywords_list:
  - "冷氣保養"
  - "冷氣檢查"
  - "檢查冷氣"
  - "VRV"
  - "VRF"
  - "大金"
  - "大金VRV"
  - "冷氣維修"
  - "維修冷氣"
  - "洗冷氣"
  - "冷氣工程"
  - "冷氣清洗"
  - "冷氣"
  - "清洗冷氣"
  - "冷氣安裝"
  - "冷氣公司"

# 也可以使用逗号分隔的字符串形式
# keywords: "冷氣保養,冷氣檢查,檢查冷氣,VRV,VRF,大金,大金VRV,冷氣維修,維修冷氣,洗冷氣,冷氣工程,冷氣清洗,冷氣,清洗冷氣,冷氣安裝,冷氣公司"
