# SEO研究工具配置文件示例

# 目标网站域名（必填）
domain: "example.com"

# 关键词设置（必填，可以使用以下两种方式之一）
# 使用逗号分隔的字符串
keywords: "SEO优化,网站推广,数字营销,搜索引擎优化"

# 搜索引擎设置
search_engine: "google"  # 可选值: "google" 或 "bing"，默认为 "google"

# 搜索区域设置
region: "com.hk"  # 例如: "com"、"com.hk"、"co.jp"，默认为 "com"

# 搜索页数设置
pages: 5  # 默认为 3

# 请求延迟设置（秒）
delay_min: 2.0  # 最小延迟时间，默认为 2.0
delay_max: 5.0  # 最大延迟时间，默认为 5.0

# 输出文件设置
output: "seo_analysis_results.xlsx"  # 默认为 "seo_analysis_results.xlsx" 